import base64
import streamlit as st
cities_list = [
"Canada: Toronto (Pearson International Airport)",
"Canada: Vancouver (Vancouver International Airport)",
"Canada: Montreal (Trudeau International Airport)",
"Canada: Calgary (Calgary International Airport)",
"Canada: Edmonton (Edmonton International Airport)",
"United States: Atlanta (Hartsfield-Jackson Atlanta International Airport)",
"United States: Baltimore/Washington (BWI Thurgood Marshall Airport)",
"United States: Boston (Logan International Airport)",
"United States: Chicago (O'Hare International Airport, Midway International Airport)",
"United States: Dallas/Fort Worth (Dallas/Fort Worth International Airport)",
"United States: Denver (Denver International Airport)",
"United States: Houston (George Bush Intercontinental Airport, William P. Hobby Airport)",
"United States: Los Angeles (Los Angeles International Airport)",
"United States: Miami (Miami International Airport)",
"United States: Minneapolis-Saint Paul (Minneapolis-Saint Paul International Airport)",
"United States: Newark (Newark Liberty International Airport)",
"United States: New York City (John F. Kennedy International Airport, LaGuardia Airport)",
"United States: Orlando (Orlando International Airport)",
"United States: Philadelphia (Philadelphia International Airport)",
"United States: Phoenix (Phoenix Sky Harbor International Airport)",
"United States: Portland (Portland International Airport)",
"United States: Salt Lake City (Salt Lake City International Airport)",
"United States: San Francisco (San Francisco International Airport)",
"United States: Seattle (Seattle-Tacoma International Airport)",
"United States: Tampa (Tampa International Airport)",
"United States: Washington, D.C. (Ronald Reagan Washington National Airport, Washington Dulles International Airport)",
"Austria: Vienna (Vienna International Airport)",
"Belgium: Brussels (Brussels Airport)",
"Czech Republic: Prague (Václav Havel Airport Prague)",
"Denmark: Copenhagen (Copenhagen Airport)",
"Finland: Helsinki (Helsinki-Vantaa Airport)",
"France: Paris (Charles de Gaulle Airport, Orly Airport)",
"France: Lyon (Lyon-Saint-Exupéry Airport)",
"Germany: Berlin (Berlin Brandenburg Airport)",
"Germany: Frankfurt (Frankfurt Airport)",
"Germany: Munich (Munich Airport)",
"Germany: Cologne/Bonn (Cologne Bonn Airport)",
"Germany: Düsseldorf (Düsseldorf Airport)",
"Germany: Hamburg (Hamburg Airport)",
"Germany: Stuttgart (Stuttgart Airport)",
"Hungary: Budapest (Budapest Ferenc Liszt International Airport)",
"Ireland: Dublin (Dublin Airport)",
"Italy: Rome (Leonardo da Vinci–Fiumicino Airport, Ciampino Airport)",
"Italy: Milan (Malpensa Airport, Linate Airport, Orio al Serio International Airport)",
"Netherlands: Amsterdam (Amsterdam Airport Schiphol)",
"Norway: Oslo (Oslo Airport, Gardermoen)",
"Poland: Warsaw (Warsaw Chopin Airport)",
"Portugal: Lisbon (Lisbon Portela Airport)",
"Portugal: Porto (Francisco Sá Carneiro Airport)",
"Russia: Moscow (Sheremetyevo International Airport, Domodedovo International Airport, Vnukovo International Airport)",
"Russia: Saint Petersburg (Pulkovo International Airport)",
"Spain: Madrid (Adolfo Suárez Madrid–Barajas Airport)",
"Spain: Barcelona (Josep Tarradellas Barcelona–El Prat Airport)",
"Spain: Valencia (Valencia Airport)",
"Spain: Seville (Seville Airport)",
"Spain: Bilbao (Bilbao Airport)",
"Sweden: Stockholm (Stockholm Arlanda Airport)",
"Switzerland: Zurich (Zurich Airport)",
"Switzerland: Geneva (Geneva Airport)",
"United Kingdom: London (Heathrow Airport, Gatwick Airport, London City Airport, Stansted Airport, Luton Airport)",
"United Kingdom: Manchester (Manchester Airport)",
"United Kingdom: Edinburgh (Edinburgh Airport)",
"United Kingdom: Birmingham (Birmingham Airport)",
"United Kingdom: Glasgow (Glasgow Airport)",
"China: Beijing (Beijing Capital International Airport, Beijing Daxing International Airport)",
"China: Shanghai (Shanghai Pudong International Airport, Shanghai Hongqiao International Airport)",
"China: Guangzhou (Guangzhou Baiyun International Airport)",
"China: Shenzhen (Shenzhen Bao'an International Airport)",
"China: Hong Kong (Hong Kong International Airport)",
"India: Delhi (Indira Gandhi International Airport)",
"India: Mumbai (Chhatrapati Shivaji Maharaj International Airport)",
"India: Bangalore (Kempegowda International Airport)",
"India: Hyderabad (Rajiv Gandhi International Airport)",
"India: Chennai (Chennai International Airport)",
"Japan: Tokyo (Narita International Airport, Haneda Airport)",
"Japan: Osaka (Kansai International Airport, Osaka International Airport)",
"Japan: Nagoya (Chubu Centrair International Airport)",
"Japan: Fukuoka (Fukuoka Airport)",
"Japan: Sapporo (New Chitose Airport)",
"Malaysia: Kuala Lumpur (Kuala Lumpur International Airport)",
"Singapore: Singapore (Changi Airport)",
"South Korea: Seoul (Incheon International Airport, Gimpo International Airport)",
"South Korea: Busan (Gimhae International Airport)",
"Taiwan: Taipei (Taoyuan International Airport)",
"Thailand: Bangkok (Suvarnabhumi Airport, Don Mueang International Airport)",
"United Arab Emirates: Dubai (Dubai International Airport)",
"United Arab Emirates: Abu Dhabi (Abu Dhabi International Airport)",
"Australia: Sydney (Sydney Airport)",
"Australia: Melbourne (Melbourne Airport)",
"Australia: Brisbane (Brisbane Airport)",
"Australia: Perth (Perth Airport)",
"Australia: Adelaide (Adelaide Airport)",
"Australia: Gold Coast (Gold Coast Airport)",
"South Africa: Johannesburg (O.R. Tambo International Airport)",
"South Africa: Cape Town (Cape Town International Airport)",
"Brazil: São Paulo (São Paulo/Guarulhos International Airport)",
"Brazil: Rio de Janeiro (Rio de Janeiro/Galeão International Airport)",
"Mexico: Mexico City (Mexico City International Airport)",
]
countries_list = [
"Afghanistan",
"Albania",
"Algeria",
"Andorra",
"Angola",
"Antigua and Barbuda",
"Argentina",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bhutan",
"Bolivia",
"Bosnia and Herzegovina",
"Botswana",
"Brazil",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Côte d'Ivoire",
"Cabo Verde",
"Cambodia",
"Cameroon",
"Canada",
"Central African Republic",
"Chad",
"Chile",
"China",
"Colombia",
"Comoros",
"Congo(Congo - Brazzaville)",
"Costa Rica",
"Croatia",
"Cuba",
"Cyprus",
"Czechia(Czech Republic)",
"Democratic Republic of the Congo",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Eswatini(fmr.Swaziland)",
"Ethiopia",
"Fiji",
"Finland",
"France",
"Gabon",
"Gambia",
"Georgia",
"Germany",
"Ghana",
"Greece",
"Grenada",
"Guatemala",
"Guinea",
"Guinea - Bissau",
"Guyana",
"Haiti",
"Holy",
"See",
"Honduras",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran",
"Iraq",
"Ireland",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Kuwait",
"Kyrgyzstan",
"Laos",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall",
"Islands",
"Mauritania",
"Mauritius",
"Mexico",
"Micronesia",
"Moldova",
"Monaco",
"Mongolia",
"Montenegro",
"Morocco",
"Mozambique",
"Myanmar(formerly Burma)",
"Namibia",
"Nauru",
"Nepal",
"Netherlands",
"New Zealand",
"Nicaragua",
"Niger",
"Nigeria",
"North Korea",
"North Macedonia",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Palestine State",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines",
"Poland",
"Portugal",
"Qatar",
"Romania",
"Russia",
"Rwanda",
"Saint Kitts and Nevis",
"Saint Lucia",
"Saint Vincent and the Grenadines",
"Samoa",
"San Marino",
"Sao Tome and Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Korea",
"South Sudan",
"Spain",
"Sri Lanka",
"Sudan",
"Suriname",
"Sweden",
"Switzerland",
"Syria",
"Tajikistan",
"Tanzania",
"Thailand",
"Timor - Leste",
"Togo",
"Tonga",
"Trinidad and Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates",
"United Kingdom",
"United States of America",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela",
"Vietnam",
"Yemen",
"Zambia",
"Zimbabwe",
]
airlines_list = ["Aegean Airlines",
"Aer Lingus",
"Aeroflot",
"Aerolineas Argentinas",
"Aeromexico",
"Air Arabia",
"Air Astana",
"Air Austral",
"Air Baltic",
"Air Belgium",
"Air Canada",
"Air Caraibes",
"Air China",
"Air Corsica",
"Air Dolomiti",
"Air Europa",
"Air France",
"Air India",
"Air India Express",
"Air Macau",
"Air Malta",
"Air Mauritius",
"Air Namibia",
"Air New Zealand",
"Air North",
"Air Seoul",
"Air Serbia",
"Air Tahiti Nui",
"Air Transat",
"Air Vanuatu",
"AirAsia",
"AirAsia X",
"Aircalin",
"Alaska Airlines",
"Alitalia",
"Allegiant",
"American Airlines",
"ANA",
"Asiana",
"Austrian",
"Azerbaijan Hava Yollary",
"Azores Airlines",
"Azul",
"Bamboo Airways",
"Bangkok Airways",
"British Airways",
"Brussels Airlines",
"Caribbean Airlines",
"Cathay Dragon",
"Cathay Pacific",
"Cayman Airways",
"CEBU Pacific Air",
"China Airlines",
"China Eastern",
"China Southern",
"Condor",
"Copa Airlines",
"Croatia Airlines",
"Czech Airlines",
"Delta",
"easyJet",
"Edelweiss Air",
"Egyptair",
"EL AL",
"Emirates",
"Ethiopian Airlines",
"Etihad",
"Eurowings",
"EVA Air",
"Fiji Airways",
"Finnair",
"flydubai",
"FlyOne",
"French bee",
"Frontier",
"Garuda Indonesia",
"Gol",
"Gulf Air",
"Hainan Airlines",
"Hawaiian Airlines",
"Helvetic Airways",
"HK Express",
"Hong Kong Airlines",
"Iberia",
"Icelandair",
"IndiGo Airlines",
"InterJet",
"Japan Airlines",
"Jeju Air",
"Jet2",
"JetBlue",
"Jetstar",
"Jin Air",
"Kenya Airways",
"KLM",
"Korean Air",
"Kulula",
"La Compagnie",
"LATAM",
"Lion Airlines",
"LOT Polish Airlines",
"Lufthansa",
"Luxair",
"Malaysia Airlines",
"Mango",
"Middle East Airlines",
"Nok Air",
"Nordwind Airlines",
"Norwegian Air International",
"Norwegian Air Shuttle",
"Norwegian Air Sweden",
"Norwegian Air UK",
"Oman Air",
"Pakistan International Airlines",
"Peach",
"Pegasus Airlines",
"Philippine Airlines",
"Porter",
"Qantas",
"Qatar Airways",
"Regional Express",
"Rossiya - Russian Airlines",
"Royal Air Maroc",
"Royal Brunei",
"Royal Jordanian",
"RwandAir",
"Ryanair",
"S7 Airlines",
"SAS",
"Saudia",
"Scoot Airlines",
"Shanghai Airlines",
"Silkair",
"Silver",
"Singapore Airlines",
"Skylanes",
"South African Airways",
"Southwest",
"SpiceJet",
"Spirit",
"Spring Airlines",
"Spring Japan",
"SriLankan Airlines",
"Sun Country",
"Sunclass Airlines",
"Sunwing",
"SWISS",
"Swoop",
"TAAG",
"TACA",
"TAP Portugal",
"THAI",
"tigerair Australia",
"Transavia Airlines",
"TUI UK",
"TUIfly",
"Tunis Air",
"Turkish Airlines",
"Ukraine International",
"United",
"Ural Airlines",
"UTair Aviation",
"Uzbekistan Airways",
"Vietnam Airlines",
"Virgin Atlantic",
"Virgin Australia",
"Vistara",
"Viva Aerobus",
"Volaris",
"Volotea",
"Vueling Airlines",
"WestJet",
"Wizzair",
"Xiamen Airlines",
]

@st.cache_data()
def get_base64_of_bin_file(bin_file):
    with open(bin_file, 'rb') as f:
        data = f.read()
    return base64.b64encode(data).decode()


def set_png_as_page_bg(png_file):
    bin_str = get_base64_of_bin_file(png_file)
    page_bg_img = '''
    <style>
    body {
    background-image: url("data:image/png;base64,%s");
    background-size: cover;
    }
    </style>
    ''' % bin_str

    st.markdown(page_bg_img, unsafe_allow_html=True)
    return


def set_bg_hack_url():
    '''
    A function to unpack an image from url and set as bg.
    Returns
    -------
    The background.
    '''

    st.markdown(
        f"""
         <style>
         .stApp {{
             background: url("https://static.vecteezy.com/system/resources/thumbnails/043/191/561/small_2x/airplane-side-view-flying-above-the-clouds-with-blue-sky-background-illustration-vector.jpg");
             background-size: cover
         }}
         </style>
         """,
        unsafe_allow_html=True
    )
